window.ELEMENTOS = [
  {
    "id": "h",
    "nome": "Hidrogênio",
    "simbolo": "H",
    "numeroAtomico": 1,
    "barcode": 1,
    "protons": 1,
    "neutrons": 0,
    "eletrons": 1,
    "numeroMassa": 1,
    "isotopoReferencia": "¹H",
    "massaAtomica": "1,008 u",
    "camadas": [
      1
    ],
    "distribuicao": "1",
    "grupo": 1,
    "periodo": 1,
    "bloco": "s",
    "classificacao": "Não metal"
  },
  {
    "id": "he",
    "nome": "Hélio",
    "simbolo": "He",
    "numeroAtomico": 2,
    "barcode": 2,
    "protons": 2,
    "neutrons": 2,
    "eletrons": 2,
    "numeroMassa": 4,
    "isotopoReferencia": "⁴He",
    "massaAtomica": "4,003 u",
    "camadas": [
      2
    ],
    "distribuicao": "2",
    "grupo": 18,
    "periodo": 1,
    "bloco": "s",
    "classificacao": "Gás nobre"
  },
  {
    "id": "li",
    "nome": "Lítio",
    "simbolo": "Li",
    "numeroAtomico": 3,
    "barcode": 3,
    "protons": 3,
    "neutrons": 4,
    "eletrons": 3,
    "numeroMassa": 7,
    "isotopoReferencia": "⁷Li",
    "massaAtomica": "6,94 u",
    "camadas": [
      2,
      1
    ],
    "distribuicao": "2–1",
    "grupo": 1,
    "periodo": 2,
    "bloco": "s",
    "classificacao": "Metal alcalino"
  },
  {
    "id": "be",
    "nome": "Berílio",
    "simbolo": "Be",
    "numeroAtomico": 4,
    "barcode": 4,
    "protons": 4,
    "neutrons": 5,
    "eletrons": 4,
    "numeroMassa": 9,
    "isotopoReferencia": "⁹Be",
    "massaAtomica": "9,012 u",
    "camadas": [
      2,
      2
    ],
    "distribuicao": "2–2",
    "grupo": 2,
    "periodo": 2,
    "bloco": "s",
    "classificacao": "Metal alcalino-terroso"
  },
  {
    "id": "b",
    "nome": "Boro",
    "simbolo": "B",
    "numeroAtomico": 5,
    "barcode": 5,
    "protons": 5,
    "neutrons": 6,
    "eletrons": 5,
    "numeroMassa": 11,
    "isotopoReferencia": "¹¹B",
    "massaAtomica": "10,81 u",
    "camadas": [
      2,
      3
    ],
    "distribuicao": "2–3",
    "grupo": 13,
    "periodo": 2,
    "bloco": "p",
    "classificacao": "Metaloide"
  },
  {
    "id": "c",
    "nome": "Carbono",
    "simbolo": "C",
    "numeroAtomico": 6,
    "barcode": 206,
    "protons": 6,
    "neutrons": 6,
    "eletrons": 6,
    "numeroMassa": 12,
    "isotopoReferencia": "¹²C",
    "massaAtomica": "12,01 u",
    "camadas": [
      2,
      4
    ],
    "distribuicao": "2–4",
    "grupo": 14,
    "periodo": 2,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "n",
    "nome": "Nitrogênio",
    "simbolo": "N",
    "numeroAtomico": 7,
    "barcode": 7,
    "protons": 7,
    "neutrons": 7,
    "eletrons": 7,
    "numeroMassa": 14,
    "isotopoReferencia": "¹⁴N",
    "massaAtomica": "14,01 u",
    "camadas": [
      2,
      5
    ],
    "distribuicao": "2–5",
    "grupo": 15,
    "periodo": 2,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "o",
    "nome": "Oxigênio",
    "simbolo": "O",
    "numeroAtomico": 8,
    "barcode": 8,
    "protons": 8,
    "neutrons": 8,
    "eletrons": 8,
    "numeroMassa": 16,
    "isotopoReferencia": "¹⁶O",
    "massaAtomica": "16,00 u",
    "camadas": [
      2,
      6
    ],
    "distribuicao": "2–6",
    "grupo": 16,
    "periodo": 2,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "f",
    "nome": "Flúor",
    "simbolo": "F",
    "numeroAtomico": 9,
    "barcode": 9,
    "protons": 9,
    "neutrons": 10,
    "eletrons": 9,
    "numeroMassa": 19,
    "isotopoReferencia": "¹⁹F",
    "massaAtomica": "19,00 u",
    "camadas": [
      2,
      7
    ],
    "distribuicao": "2–7",
    "grupo": 17,
    "periodo": 2,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "ne",
    "nome": "Neônio",
    "simbolo": "Ne",
    "numeroAtomico": 10,
    "barcode": 10,
    "protons": 10,
    "neutrons": 10,
    "eletrons": 10,
    "numeroMassa": 20,
    "isotopoReferencia": "²⁰Ne",
    "massaAtomica": "20,18 u",
    "camadas": [
      2,
      8
    ],
    "distribuicao": "2–8",
    "grupo": 18,
    "periodo": 2,
    "bloco": "p",
    "classificacao": "Gás nobre"
  },
  {
    "id": "na",
    "nome": "Sódio",
    "simbolo": "Na",
    "numeroAtomico": 11,
    "barcode": 11,
    "protons": 11,
    "neutrons": 12,
    "eletrons": 11,
    "numeroMassa": 23,
    "isotopoReferencia": "²³Na",
    "massaAtomica": "22,99 u",
    "camadas": [
      2,
      8,
      1
    ],
    "distribuicao": "2–8–1",
    "grupo": 1,
    "periodo": 3,
    "bloco": "s",
    "classificacao": "Metal alcalino",
    "isotopos": [
      {
        "massa": 22,
        "neutrons": 11,
        "simboloNuclear": "²²Na",
        "nome": "Sódio-22",
        "estabilidade": "Radioativo",
        "meiaVida": "2,602 anos",
        "observacao": "Radioisótopo do sódio."
      },
      {
        "massa": 23,
        "neutrons": 12,
        "simboloNuclear": "²³Na",
        "nome": "Sódio-23",
        "estabilidade": "Estável",
        "meiaVida": "Estável — não possui meia-vida radioativa",
        "observacao": "É o isótopo estável do sódio."
      },
      {
        "massa": 24,
        "neutrons": 13,
        "simboloNuclear": "²⁴Na",
        "nome": "Sódio-24",
        "estabilidade": "Radioativo",
        "meiaVida": "aprox. 15 horas",
        "observacao": "Radioisótopo de meia-vida curta."
      }
    ],
    "estadosEletronicos": [
      {
        "eletrons": 10,
        "carga": 1,
        "simbolo": "Na⁺",
        "nome": "Cátion sódio",
        "classificacao": "Cátion",
        "camadas": [
          2,
          8
        ],
        "distribuicao": "2–8",
        "observacao": "O sódio perdeu 1 elétron. Como possui 11 prótons e 10 elétrons, sua carga resultante é +1."
      },
      {
        "eletrons": 11,
        "carga": 0,
        "simbolo": "Na",
        "nome": "Átomo neutro de sódio",
        "classificacao": "Átomo neutro",
        "camadas": [
          2,
          8,
          1
        ],
        "distribuicao": "2–8–1",
        "observacao": "O número de prótons e elétrons é igual. Portanto, a carga elétrica resultante é zero."
      }
    ]
  },
  {
    "id": "mg",
    "nome": "Magnésio",
    "simbolo": "Mg",
    "numeroAtomico": 12,
    "barcode": 12,
    "protons": 12,
    "neutrons": 12,
    "eletrons": 12,
    "numeroMassa": 24,
    "isotopoReferencia": "²⁴Mg",
    "massaAtomica": "24,305 u",
    "camadas": [
      2,
      8,
      2
    ],
    "distribuicao": "2–8–2",
    "grupo": 2,
    "periodo": 3,
    "bloco": "s",
    "classificacao": "Metal alcalino-terroso"
  },
  {
    "id": "al",
    "nome": "Alumínio",
    "simbolo": "Al",
    "numeroAtomico": 13,
    "barcode": 13,
    "protons": 13,
    "neutrons": 14,
    "eletrons": 13,
    "numeroMassa": 27,
    "isotopoReferencia": "²⁷Al",
    "massaAtomica": "26,982 u",
    "camadas": [
      2,
      8,
      3
    ],
    "distribuicao": "2–8–3",
    "grupo": 13,
    "periodo": 3,
    "bloco": "p",
    "classificacao": "Metal"
  },
  {
    "id": "si",
    "nome": "Silício",
    "simbolo": "Si",
    "numeroAtomico": 14,
    "barcode": 14,
    "protons": 14,
    "neutrons": 14,
    "eletrons": 14,
    "numeroMassa": 28,
    "isotopoReferencia": "²⁸Si",
    "massaAtomica": "28,085 u",
    "camadas": [
      2,
      8,
      4
    ],
    "distribuicao": "2–8–4",
    "grupo": 14,
    "periodo": 3,
    "bloco": "p",
    "classificacao": "Metaloide"
  },
  {
    "id": "p",
    "nome": "Fósforo",
    "simbolo": "P",
    "numeroAtomico": 15,
    "barcode": 15,
    "protons": 15,
    "neutrons": 16,
    "eletrons": 15,
    "numeroMassa": 31,
    "isotopoReferencia": "³¹P",
    "massaAtomica": "30,974 u",
    "camadas": [
      2,
      8,
      5
    ],
    "distribuicao": "2–8–5",
    "grupo": 15,
    "periodo": 3,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "s",
    "nome": "Enxofre",
    "simbolo": "S",
    "numeroAtomico": 16,
    "barcode": 16,
    "protons": 16,
    "neutrons": 16,
    "eletrons": 16,
    "numeroMassa": 32,
    "isotopoReferencia": "³²S",
    "massaAtomica": "32,06 u",
    "camadas": [
      2,
      8,
      6
    ],
    "distribuicao": "2–8–6",
    "grupo": 16,
    "periodo": 3,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "cl",
    "nome": "Cloro",
    "simbolo": "Cl",
    "numeroAtomico": 17,
    "barcode": 17,
    "protons": 17,
    "neutrons": 18,
    "eletrons": 17,
    "numeroMassa": 35,
    "isotopoReferencia": "³⁵Cl",
    "massaAtomica": "35,45 u",
    "camadas": [
      2,
      8,
      7
    ],
    "distribuicao": "2–8–7",
    "grupo": 17,
    "periodo": 3,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "ar",
    "nome": "Argônio",
    "simbolo": "Ar",
    "numeroAtomico": 18,
    "barcode": 18,
    "protons": 18,
    "neutrons": 22,
    "eletrons": 18,
    "numeroMassa": 40,
    "isotopoReferencia": "⁴⁰Ar",
    "massaAtomica": "39,95 u",
    "camadas": [
      2,
      8,
      8
    ],
    "distribuicao": "2–8–8",
    "grupo": 18,
    "periodo": 3,
    "bloco": "p",
    "classificacao": "Gás nobre"
  },
  {
    "id": "k",
    "nome": "Potássio",
    "simbolo": "K",
    "numeroAtomico": 19,
    "barcode": 19,
    "protons": 19,
    "neutrons": 20,
    "eletrons": 19,
    "numeroMassa": 39,
    "isotopoReferencia": "³⁹K",
    "massaAtomica": "39,10 u",
    "camadas": [
      2,
      8,
      8,
      1
    ],
    "distribuicao": "2–8–8–1",
    "grupo": 1,
    "periodo": 4,
    "bloco": "s",
    "classificacao": "Metal alcalino"
  },
  {
    "id": "ca",
    "nome": "Cálcio",
    "simbolo": "Ca",
    "numeroAtomico": 20,
    "barcode": 20,
    "protons": 20,
    "neutrons": 20,
    "eletrons": 20,
    "numeroMassa": 40,
    "isotopoReferencia": "⁴⁰Ca",
    "massaAtomica": "40,078 u",
    "camadas": [
      2,
      8,
      8,
      2
    ],
    "distribuicao": "2–8–8–2",
    "grupo": 2,
    "periodo": 4,
    "bloco": "s",
    "classificacao": "Metal alcalino-terroso"
  },
  {
    "id": "sc",
    "nome": "Escândio",
    "simbolo": "Sc",
    "numeroAtomico": 21,
    "barcode": 21,
    "protons": 21,
    "neutrons": 24,
    "eletrons": 21,
    "numeroMassa": 45,
    "isotopoReferencia": "⁴⁵Sc",
    "massaAtomica": "44,96 u",
    "camadas": [
      2,
      8,
      9,
      2
    ],
    "distribuicao": "2–8–9–2",
    "grupo": 3,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "ti",
    "nome": "Titânio",
    "simbolo": "Ti",
    "numeroAtomico": 22,
    "barcode": 22,
    "protons": 22,
    "neutrons": 26,
    "eletrons": 22,
    "numeroMassa": 48,
    "isotopoReferencia": "⁴⁸Ti",
    "massaAtomica": "47,87 u",
    "camadas": [
      2,
      8,
      10,
      2
    ],
    "distribuicao": "2–8–10–2",
    "grupo": 4,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "v",
    "nome": "Vanádio",
    "simbolo": "V",
    "numeroAtomico": 23,
    "barcode": 23,
    "protons": 23,
    "neutrons": 28,
    "eletrons": 23,
    "numeroMassa": 51,
    "isotopoReferencia": "⁵¹V",
    "massaAtomica": "50,94 u",
    "camadas": [
      2,
      8,
      11,
      2
    ],
    "distribuicao": "2–8–11–2",
    "grupo": 5,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "cr",
    "nome": "Cromo",
    "simbolo": "Cr",
    "numeroAtomico": 24,
    "barcode": 24,
    "protons": 24,
    "neutrons": 28,
    "eletrons": 24,
    "numeroMassa": 52,
    "isotopoReferencia": "⁵²Cr",
    "massaAtomica": "52,00 u",
    "camadas": [
      2,
      8,
      13,
      1
    ],
    "distribuicao": "2–8–13–1",
    "grupo": 6,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "mn",
    "nome": "Manganês",
    "simbolo": "Mn",
    "numeroAtomico": 25,
    "barcode": 25,
    "protons": 25,
    "neutrons": 30,
    "eletrons": 25,
    "numeroMassa": 55,
    "isotopoReferencia": "⁵⁵Mn",
    "massaAtomica": "54,94 u",
    "camadas": [
      2,
      8,
      13,
      2
    ],
    "distribuicao": "2–8–13–2",
    "grupo": 7,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "fe",
    "nome": "Ferro",
    "simbolo": "Fe",
    "numeroAtomico": 26,
    "barcode": 26,
    "protons": 26,
    "neutrons": 30,
    "eletrons": 26,
    "numeroMassa": 56,
    "isotopoReferencia": "⁵⁶Fe",
    "massaAtomica": "55,85 u",
    "camadas": [
      2,
      8,
      14,
      2
    ],
    "distribuicao": "2–8–14–2",
    "grupo": 8,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "co",
    "nome": "Cobalto",
    "simbolo": "Co",
    "numeroAtomico": 27,
    "barcode": 27,
    "protons": 27,
    "neutrons": 32,
    "eletrons": 27,
    "numeroMassa": 59,
    "isotopoReferencia": "⁵⁹Co",
    "massaAtomica": "58,93 u",
    "camadas": [
      2,
      8,
      15,
      2
    ],
    "distribuicao": "2–8–15–2",
    "grupo": 9,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "ni",
    "nome": "Níquel",
    "simbolo": "Ni",
    "numeroAtomico": 28,
    "barcode": 28,
    "protons": 28,
    "neutrons": 30,
    "eletrons": 28,
    "numeroMassa": 58,
    "isotopoReferencia": "⁵⁸Ni",
    "massaAtomica": "58,69 u",
    "camadas": [
      2,
      8,
      16,
      2
    ],
    "distribuicao": "2–8–16–2",
    "grupo": 10,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "cu",
    "nome": "Cobre",
    "simbolo": "Cu",
    "numeroAtomico": 29,
    "barcode": 29,
    "protons": 29,
    "neutrons": 34,
    "eletrons": 29,
    "numeroMassa": 63,
    "isotopoReferencia": "⁶³Cu",
    "massaAtomica": "63,55 u",
    "camadas": [
      2,
      8,
      18,
      1
    ],
    "distribuicao": "2–8–18–1",
    "grupo": 11,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "zn",
    "nome": "Zinco",
    "simbolo": "Zn",
    "numeroAtomico": 30,
    "barcode": 30,
    "protons": 30,
    "neutrons": 35,
    "eletrons": 30,
    "numeroMassa": 65,
    "isotopoReferencia": "⁶⁵Zn",
    "massaAtomica": "65,38 u",
    "camadas": [
      2,
      8,
      18,
      2
    ],
    "distribuicao": "2–8–18–2",
    "grupo": 12,
    "periodo": 4,
    "bloco": "d",
    "classificacao": "Metal do grupo 12"
  },
  {
    "id": "ga",
    "nome": "Gálio",
    "simbolo": "Ga",
    "numeroAtomico": 31,
    "barcode": 31,
    "protons": 31,
    "neutrons": 38,
    "eletrons": 31,
    "numeroMassa": 69,
    "isotopoReferencia": "⁶⁹Ga",
    "massaAtomica": "69,72 u",
    "camadas": [
      2,
      8,
      18,
      3
    ],
    "distribuicao": "2–8–18–3",
    "grupo": 13,
    "periodo": 4,
    "bloco": "p",
    "classificacao": "Metal do grupo 13"
  },
  {
    "id": "ge",
    "nome": "Germânio",
    "simbolo": "Ge",
    "numeroAtomico": 32,
    "barcode": 32,
    "protons": 32,
    "neutrons": 41,
    "eletrons": 32,
    "numeroMassa": 73,
    "isotopoReferencia": "⁷³Ge",
    "massaAtomica": "72,63 u",
    "camadas": [
      2,
      8,
      18,
      4
    ],
    "distribuicao": "2–8–18–4",
    "grupo": 14,
    "periodo": 4,
    "bloco": "p",
    "classificacao": "Semimetal"
  },
  {
    "id": "as",
    "nome": "Arsênio",
    "simbolo": "As",
    "numeroAtomico": 33,
    "barcode": 33,
    "protons": 33,
    "neutrons": 42,
    "eletrons": 33,
    "numeroMassa": 75,
    "isotopoReferencia": "⁷⁵As",
    "massaAtomica": "74,92 u",
    "camadas": [
      2,
      8,
      18,
      5
    ],
    "distribuicao": "2–8–18–5",
    "grupo": 15,
    "periodo": 4,
    "bloco": "p",
    "classificacao": "Semimetal"
  },
  {
    "id": "se",
    "nome": "Selênio",
    "simbolo": "Se",
    "numeroAtomico": 34,
    "barcode": 34,
    "protons": 34,
    "neutrons": 45,
    "eletrons": 34,
    "numeroMassa": 79,
    "isotopoReferencia": "⁷⁹Se",
    "massaAtomica": "78,97 u",
    "camadas": [
      2,
      8,
      18,
      6
    ],
    "distribuicao": "2–8–18–6",
    "grupo": 16,
    "periodo": 4,
    "bloco": "p",
    "classificacao": "Não metal"
  },
  {
    "id": "br",
    "nome": "Bromo",
    "simbolo": "Br",
    "numeroAtomico": 35,
    "barcode": 35,
    "protons": 35,
    "neutrons": 45,
    "eletrons": 35,
    "numeroMassa": 80,
    "isotopoReferencia": "⁸⁰Br",
    "massaAtomica": "79,90 u",
    "camadas": [
      2,
      8,
      18,
      7
    ],
    "distribuicao": "2–8–18–7",
    "grupo": 17,
    "periodo": 4,
    "bloco": "p",
    "classificacao": "Halogênio"
  },
  {
    "id": "kr",
    "nome": "Criptônio",
    "simbolo": "Kr",
    "numeroAtomico": 36,
    "barcode": 36,
    "protons": 36,
    "neutrons": 48,
    "eletrons": 36,
    "numeroMassa": 84,
    "isotopoReferencia": "⁸⁴Kr",
    "massaAtomica": "83,80 u",
    "camadas": [
      2,
      8,
      18,
      8
    ],
    "distribuicao": "2–8–18–8",
    "grupo": 18,
    "periodo": 4,
    "bloco": "p",
    "classificacao": "Gás nobre"
  },
  {
    "id": "rb",
    "nome": "Rubídio",
    "simbolo": "Rb",
    "numeroAtomico": 37,
    "barcode": 37,
    "protons": 37,
    "neutrons": 48,
    "eletrons": 37,
    "numeroMassa": 85,
    "isotopoReferencia": "⁸⁵Rb",
    "massaAtomica": "85,47 u",
    "camadas": [
      2,
      8,
      18,
      8,
      1
    ],
    "distribuicao": "2–8–18–8–1",
    "grupo": 1,
    "periodo": 5,
    "bloco": "s",
    "classificacao": "Metal alcalino"
  },
  {
    "id": "sr",
    "nome": "Estrôncio",
    "simbolo": "Sr",
    "numeroAtomico": 38,
    "barcode": 38,
    "protons": 38,
    "neutrons": 50,
    "eletrons": 38,
    "numeroMassa": 88,
    "isotopoReferencia": "⁸⁸Sr",
    "massaAtomica": "87,62 u",
    "camadas": [
      2,
      8,
      18,
      8,
      2
    ],
    "distribuicao": "2–8–18–8–2",
    "grupo": 2,
    "periodo": 5,
    "bloco": "s",
    "classificacao": "Metal alcalino-terroso"
  },
  {
    "id": "y",
    "nome": "Ítrio",
    "simbolo": "Y",
    "numeroAtomico": 39,
    "barcode": 39,
    "protons": 39,
    "neutrons": 50,
    "eletrons": 39,
    "numeroMassa": 89,
    "isotopoReferencia": "⁸⁹Y",
    "massaAtomica": "88,91 u",
    "camadas": [
      2,
      8,
      18,
      9,
      2
    ],
    "distribuicao": "2–8–18–9–2",
    "grupo": 3,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "zr",
    "nome": "Zircônio",
    "simbolo": "Zr",
    "numeroAtomico": 40,
    "barcode": 40,
    "protons": 40,
    "neutrons": 50,
    "eletrons": 40,
    "numeroMassa": 90,
    "isotopoReferencia": "⁹⁰Zr",
    "massaAtomica": "91,22 u",
    "camadas": [
      2,
      8,
      18,
      10,
      2
    ],
    "distribuicao": "2–8–18–10–2",
    "grupo": 4,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "nb",
    "nome": "Nióbio",
    "simbolo": "Nb",
    "numeroAtomico": 41,
    "barcode": 41,
    "protons": 41,
    "neutrons": 52,
    "eletrons": 41,
    "numeroMassa": 93,
    "isotopoReferencia": "⁹³Nb",
    "massaAtomica": "92,91 u",
    "camadas": [
      2,
      8,
      18,
      12,
      1
    ],
    "distribuicao": "2–8–18–12–1",
    "grupo": 5,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "mo",
    "nome": "Molibdênio",
    "simbolo": "Mo",
    "numeroAtomico": 42,
    "barcode": 42,
    "protons": 42,
    "neutrons": 54,
    "eletrons": 42,
    "numeroMassa": 96,
    "isotopoReferencia": "⁹⁶Mo",
    "massaAtomica": "95,95 u",
    "camadas": [
      2,
      8,
      18,
      13,
      1
    ],
    "distribuicao": "2–8–18–13–1",
    "grupo": 6,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "tc",
    "nome": "Tecnécio",
    "simbolo": "Tc",
    "numeroAtomico": 43,
    "barcode": 43,
    "protons": 43,
    "neutrons": 55,
    "eletrons": 43,
    "numeroMassa": 98,
    "isotopoReferencia": "⁹⁸Tc",
    "massaAtomica": "98 u",
    "camadas": [
      2,
      8,
      18,
      13,
      2
    ],
    "distribuicao": "2–8–18–13–2",
    "grupo": 7,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "ru",
    "nome": "Rutênio",
    "simbolo": "Ru",
    "numeroAtomico": 44,
    "barcode": 44,
    "protons": 44,
    "neutrons": 57,
    "eletrons": 44,
    "numeroMassa": 101,
    "isotopoReferencia": "¹⁰¹Ru",
    "massaAtomica": "101,07 u",
    "camadas": [
      2,
      8,
      18,
      15,
      1
    ],
    "distribuicao": "2–8–18–15–1",
    "grupo": 8,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "rh",
    "nome": "Ródio",
    "simbolo": "Rh",
    "numeroAtomico": 45,
    "barcode": 45,
    "protons": 45,
    "neutrons": 58,
    "eletrons": 45,
    "numeroMassa": 103,
    "isotopoReferencia": "¹⁰³Rh",
    "massaAtomica": "102,91 u",
    "camadas": [
      2,
      8,
      18,
      16,
      1
    ],
    "distribuicao": "2–8–18–16–1",
    "grupo": 9,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "pd",
    "nome": "Paládio",
    "simbolo": "Pd",
    "numeroAtomico": 46,
    "barcode": 46,
    "protons": 46,
    "neutrons": 60,
    "eletrons": 46,
    "numeroMassa": 106,
    "isotopoReferencia": "¹⁰⁶Pd",
    "massaAtomica": "106,42 u",
    "camadas": [
      2,
      8,
      18,
      18,
      0
    ],
    "distribuicao": "2–8–18–18–0",
    "grupo": 10,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição; metal do grupo da platina"
  },
  {
    "id": "ag",
    "nome": "Prata",
    "simbolo": "Ag",
    "numeroAtomico": 47,
    "barcode": 47,
    "protons": 47,
    "neutrons": 60,
    "eletrons": 47,
    "numeroMassa": 107,
    "isotopoReferencia": "¹⁰⁷Ag",
    "massaAtomica": "107,87 u",
    "camadas": [
      2,
      8,
      18,
      18,
      1
    ],
    "distribuicao": "2–8–18–18–1",
    "grupo": 11,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "cd",
    "nome": "Cádmio",
    "simbolo": "Cd",
    "numeroAtomico": 48,
    "barcode": 48,
    "protons": 48,
    "neutrons": 66,
    "eletrons": 48,
    "numeroMassa": 114,
    "isotopoReferencia": "¹¹⁴Cd",
    "massaAtomica": "112,41 u",
    "camadas": [
      2,
      8,
      18,
      18,
      2
    ],
    "distribuicao": "2–8–18–18–2",
    "grupo": 12,
    "periodo": 5,
    "bloco": "d",
    "classificacao": "Metal do grupo 12; caso especial em relação à definição estrita de metal de transição"
  },
  {
    "id": "in",
    "nome": "Índio",
    "simbolo": "In",
    "numeroAtomico": 49,
    "barcode": 49,
    "protons": 49,
    "neutrons": 66,
    "eletrons": 49,
    "numeroMassa": 115,
    "isotopoReferencia": "¹¹⁵In",
    "massaAtomica": "114,82 u",
    "camadas": [
      2,
      8,
      18,
      18,
      3
    ],
    "distribuicao": "2–8–18–18–3",
    "grupo": 13,
    "periodo": 5,
    "bloco": "p",
    "classificacao": "Metal pós-transição"
  },
  {
    "id": "sn",
    "nome": "Estanho",
    "simbolo": "Sn",
    "numeroAtomico": 50,
    "barcode": 50,
    "protons": 50,
    "neutrons": 70,
    "eletrons": 50,
    "numeroMassa": 120,
    "isotopoReferencia": "¹²⁰Sn",
    "massaAtomica": "118,71 u",
    "camadas": [
      2,
      8,
      18,
      18,
      4
    ],
    "distribuicao": "2–8–18–18–4",
    "grupo": 14,
    "periodo": 5,
    "bloco": "p",
    "classificacao": "Metal pós-transição"
  },
  {
    "id": "sb",
    "nome": "Antimônio",
    "simbolo": "Sb",
    "numeroAtomico": 51,
    "barcode": 51,
    "protons": 51,
    "neutrons": 71,
    "eletrons": 51,
    "numeroMassa": 122,
    "isotopoReferencia": "¹²²Sb",
    "massaAtomica": "121,76 u",
    "camadas": [
      2,
      8,
      18,
      18,
      5
    ],
    "distribuicao": "2–8–18–18–5",
    "grupo": 15,
    "periodo": 5,
    "bloco": "p",
    "classificacao": "Metaloide"
  },
  {
    "id": "te",
    "nome": "Telúrio",
    "simbolo": "Te",
    "numeroAtomico": 52,
    "barcode": 52,
    "protons": 52,
    "neutrons": 74,
    "eletrons": 52,
    "numeroMassa": 126,
    "isotopoReferencia": "¹²⁶Te",
    "massaAtomica": "127,60 u",
    "camadas": [
      2,
      8,
      18,
      18,
      6
    ],
    "distribuicao": "2–8–18–18–6",
    "grupo": 16,
    "periodo": 5,
    "bloco": "p",
    "classificacao": "Metaloide"
  },
  {
    "id": "i",
    "nome": "Iodo",
    "simbolo": "I",
    "numeroAtomico": 53,
    "barcode": 53,
    "protons": 53,
    "neutrons": 74,
    "eletrons": 53,
    "numeroMassa": 127,
    "isotopoReferencia": "¹²⁷I",
    "massaAtomica": "126,90 u",
    "camadas": [
      2,
      8,
      18,
      18,
      7
    ],
    "distribuicao": "2–8–18–18–7",
    "grupo": 17,
    "periodo": 5,
    "bloco": "p",
    "classificacao": "Não metal — halogênio"
  },
  {
    "id": "xe",
    "nome": "Xenônio",
    "simbolo": "Xe",
    "numeroAtomico": 54,
    "barcode": 54,
    "protons": 54,
    "neutrons": 78,
    "eletrons": 54,
    "numeroMassa": 132,
    "isotopoReferencia": "¹³²Xe",
    "massaAtomica": "131,29 u",
    "camadas": [
      2,
      8,
      18,
      18,
      8
    ],
    "distribuicao": "2–8–18–18–8",
    "grupo": 18,
    "periodo": 5,
    "bloco": "p",
    "classificacao": "Não metal — gás nobre"
  },
  {
    "id": "cs",
    "nome": "Césio",
    "simbolo": "Cs",
    "numeroAtomico": 55,
    "barcode": 55,
    "protons": 55,
    "neutrons": 78,
    "eletrons": 55,
    "numeroMassa": 133,
    "isotopoReferencia": "¹³³Cs",
    "massaAtomica": "132,905 u",
    "camadas": [
      2,
      8,
      18,
      18,
      8,
      1
    ],
    "distribuicao": "2–8–18–18–8–1",
    "grupo": 1,
    "periodo": 6,
    "bloco": "s",
    "classificacao": "Metal alcalino"
  },
  {
    "id": "ba",
    "nome": "Bário",
    "simbolo": "Ba",
    "numeroAtomico": 56,
    "barcode": 56,
    "protons": 56,
    "neutrons": 82,
    "eletrons": 56,
    "numeroMassa": 138,
    "isotopoReferencia": "¹³⁸Ba",
    "massaAtomica": "137,327 u",
    "camadas": [
      2,
      8,
      18,
      18,
      8,
      2
    ],
    "distribuicao": "2–8–18–18–8–2",
    "grupo": 2,
    "periodo": 6,
    "bloco": "s",
    "classificacao": "Metal alcalino-terroso"
  },
  {
    "id": "la",
    "nome": "Lantânio",
    "simbolo": "La",
    "numeroAtomico": 57,
    "barcode": 57,
    "protons": 57,
    "neutrons": 82,
    "eletrons": 57,
    "numeroMassa": 139,
    "isotopoReferencia": "¹³⁹La",
    "massaAtomica": "138,905 u",
    "camadas": [
      2,
      8,
      18,
      18,
      9,
      2
    ],
    "distribuicao": "2–8–18–18–9–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "ce",
    "nome": "Cério",
    "simbolo": "Ce",
    "numeroAtomico": 58,
    "barcode": 58,
    "protons": 58,
    "neutrons": 82,
    "eletrons": 58,
    "numeroMassa": 140,
    "isotopoReferencia": "¹⁴⁰Ce",
    "massaAtomica": "140,116 u",
    "camadas": [
      2,
      8,
      18,
      19,
      9,
      2
    ],
    "distribuicao": "2–8–18–19–9–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "pr",
    "nome": "Praseodímio",
    "simbolo": "Pr",
    "numeroAtomico": 59,
    "barcode": 59,
    "protons": 59,
    "neutrons": 82,
    "eletrons": 59,
    "numeroMassa": 141,
    "isotopoReferencia": "¹⁴¹Pr",
    "massaAtomica": "140,908 u",
    "camadas": [
      2,
      8,
      18,
      21,
      8,
      2
    ],
    "distribuicao": "2–8–18–21–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "nd",
    "nome": "Neodímio",
    "simbolo": "Nd",
    "numeroAtomico": 60,
    "barcode": 60,
    "protons": 60,
    "neutrons": 84,
    "eletrons": 60,
    "numeroMassa": 144,
    "isotopoReferencia": "¹⁴⁴Nd",
    "massaAtomica": "144,242 u",
    "camadas": [
      2,
      8,
      18,
      22,
      8,
      2
    ],
    "distribuicao": "2–8–18–22–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "pm",
    "nome": "Promécio",
    "simbolo": "Pm",
    "numeroAtomico": 61,
    "barcode": 61,
    "protons": 61,
    "neutrons": 84,
    "eletrons": 61,
    "numeroMassa": 145,
    "isotopoReferencia": "¹⁴⁵Pm",
    "massaAtomica": "[145]",
    "camadas": [
      2,
      8,
      18,
      23,
      8,
      2
    ],
    "distribuicao": "2–8–18–23–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara radioativa"
  },
  {
    "id": "sm",
    "nome": "Samário",
    "simbolo": "Sm",
    "numeroAtomico": 62,
    "barcode": 62,
    "protons": 62,
    "neutrons": 90,
    "eletrons": 62,
    "numeroMassa": 152,
    "isotopoReferencia": "¹⁵²Sm",
    "massaAtomica": "150,36 u",
    "camadas": [
      2,
      8,
      18,
      24,
      8,
      2
    ],
    "distribuicao": "2–8–18–24–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "eu",
    "nome": "Európio",
    "simbolo": "Eu",
    "numeroAtomico": 63,
    "barcode": 63,
    "protons": 63,
    "neutrons": 90,
    "eletrons": 63,
    "numeroMassa": 153,
    "isotopoReferencia": "¹⁵³Eu",
    "massaAtomica": "151,964 u",
    "camadas": [
      2,
      8,
      18,
      25,
      8,
      2
    ],
    "distribuicao": "2–8–18–25–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "gd",
    "nome": "Gadolínio",
    "simbolo": "Gd",
    "numeroAtomico": 64,
    "barcode": 64,
    "protons": 64,
    "neutrons": 94,
    "eletrons": 64,
    "numeroMassa": 158,
    "isotopoReferencia": "¹⁵⁸Gd",
    "massaAtomica": "157,25 u",
    "camadas": [
      2,
      8,
      18,
      25,
      9,
      2
    ],
    "distribuicao": "2–8–18–25–9–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "tb",
    "nome": "Térbio",
    "simbolo": "Tb",
    "numeroAtomico": 65,
    "barcode": 65,
    "protons": 65,
    "neutrons": 94,
    "eletrons": 65,
    "numeroMassa": 159,
    "isotopoReferencia": "¹⁵⁹Tb",
    "massaAtomica": "158,925 u",
    "camadas": [
      2,
      8,
      18,
      27,
      8,
      2
    ],
    "distribuicao": "2–8–18–27–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "dy",
    "nome": "Disprósio",
    "simbolo": "Dy",
    "numeroAtomico": 66,
    "barcode": 66,
    "protons": 66,
    "neutrons": 98,
    "eletrons": 66,
    "numeroMassa": 164,
    "isotopoReferencia": "¹⁶⁴Dy",
    "massaAtomica": "162,500 u",
    "camadas": [
      2,
      8,
      18,
      28,
      8,
      2
    ],
    "distribuicao": "2–8–18–28–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "ho",
    "nome": "Hólmio",
    "simbolo": "Ho",
    "numeroAtomico": 67,
    "barcode": 67,
    "protons": 67,
    "neutrons": 98,
    "eletrons": 67,
    "numeroMassa": 165,
    "isotopoReferencia": "¹⁶⁵Ho",
    "massaAtomica": "164,930 u",
    "camadas": [
      2,
      8,
      18,
      29,
      8,
      2
    ],
    "distribuicao": "2–8–18–29–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "er",
    "nome": "Érbio",
    "simbolo": "Er",
    "numeroAtomico": 68,
    "barcode": 68,
    "protons": 68,
    "neutrons": 98,
    "eletrons": 68,
    "numeroMassa": 166,
    "isotopoReferencia": "¹⁶⁶Er",
    "massaAtomica": "167,259 u",
    "camadas": [
      2,
      8,
      18,
      30,
      8,
      2
    ],
    "distribuicao": "2–8–18–30–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "tm",
    "nome": "Túlio",
    "simbolo": "Tm",
    "numeroAtomico": 69,
    "barcode": 69,
    "protons": 69,
    "neutrons": 100,
    "eletrons": 69,
    "numeroMassa": 169,
    "isotopoReferencia": "¹⁶⁹Tm",
    "massaAtomica": "168,934 u",
    "camadas": [
      2,
      8,
      18,
      31,
      8,
      2
    ],
    "distribuicao": "2–8–18–31–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "yb",
    "nome": "Itérbio",
    "simbolo": "Yb",
    "numeroAtomico": 70,
    "barcode": 70,
    "protons": 70,
    "neutrons": 104,
    "eletrons": 70,
    "numeroMassa": 174,
    "isotopoReferencia": "¹⁷⁴Yb",
    "massaAtomica": "173,045 u",
    "camadas": [
      2,
      8,
      18,
      32,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–8–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "f",
    "classificacao": "Metal de transição interna / terra rara"
  },
  {
    "id": "lu",
    "nome": "Lutécio",
    "simbolo": "Lu",
    "numeroAtomico": 71,
    "barcode": 71,
    "protons": 71,
    "neutrons": 104,
    "eletrons": 71,
    "numeroMassa": 175,
    "isotopoReferencia": "¹⁷⁵Lu",
    "massaAtomica": "174,967 u",
    "camadas": [
      2,
      8,
      18,
      32,
      9,
      2
    ],
    "distribuicao": "2–8–18–32–9–2",
    "grupo": 3,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição / frequentemente incluído entre os lantanídeos"
  },
  {
    "id": "hf",
    "nome": "Háfnio",
    "simbolo": "Hf",
    "numeroAtomico": 72,
    "barcode": 72,
    "protons": 72,
    "neutrons": 108,
    "eletrons": 72,
    "numeroMassa": 180,
    "isotopoReferencia": "¹⁸⁰Hf",
    "massaAtomica": "178,49 u",
    "camadas": [
      2,
      8,
      18,
      32,
      10,
      2
    ],
    "distribuicao": "2–8–18–32–10–2",
    "grupo": 4,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "ta",
    "nome": "Tântalo",
    "simbolo": "Ta",
    "numeroAtomico": 73,
    "barcode": 73,
    "protons": 73,
    "neutrons": 108,
    "eletrons": 73,
    "numeroMassa": 181,
    "isotopoReferencia": "¹⁸¹Ta",
    "massaAtomica": "180,948 u",
    "camadas": [
      2,
      8,
      18,
      32,
      11,
      2
    ],
    "distribuicao": "2–8–18–32–11–2",
    "grupo": 5,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "w",
    "nome": "Tungstênio",
    "simbolo": "W",
    "numeroAtomico": 74,
    "barcode": 74,
    "protons": 74,
    "neutrons": 110,
    "eletrons": 74,
    "numeroMassa": 184,
    "isotopoReferencia": "¹⁸⁴W",
    "massaAtomica": "183,84 u",
    "camadas": [
      2,
      8,
      18,
      32,
      12,
      2
    ],
    "distribuicao": "2–8–18–32–12–2",
    "grupo": 6,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "re",
    "nome": "Rênio",
    "simbolo": "Re",
    "numeroAtomico": 75,
    "barcode": 75,
    "protons": 75,
    "neutrons": 110,
    "eletrons": 75,
    "numeroMassa": 185,
    "isotopoReferencia": "¹⁸⁵Re",
    "massaAtomica": "186,207 u",
    "camadas": [
      2,
      8,
      18,
      32,
      13,
      2
    ],
    "distribuicao": "2–8–18–32–13–2",
    "grupo": 7,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "os",
    "nome": "Ósmio",
    "simbolo": "Os",
    "numeroAtomico": 76,
    "barcode": 76,
    "protons": 76,
    "neutrons": 116,
    "eletrons": 76,
    "numeroMassa": 192,
    "isotopoReferencia": "¹⁹²Os",
    "massaAtomica": "190,23 u",
    "camadas": [
      2,
      8,
      18,
      32,
      14,
      2
    ],
    "distribuicao": "2–8–18–32–14–2",
    "grupo": 8,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "ir",
    "nome": "Irídio",
    "simbolo": "Ir",
    "numeroAtomico": 77,
    "barcode": 77,
    "protons": 77,
    "neutrons": 116,
    "eletrons": 77,
    "numeroMassa": 193,
    "isotopoReferencia": "¹⁹³Ir",
    "massaAtomica": "192,217 u",
    "camadas": [
      2,
      8,
      18,
      32,
      15,
      2
    ],
    "distribuicao": "2–8–18–32–15–2",
    "grupo": 9,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "pt",
    "nome": "Platina",
    "simbolo": "Pt",
    "numeroAtomico": 78,
    "barcode": 78,
    "protons": 78,
    "neutrons": 117,
    "eletrons": 78,
    "numeroMassa": 195,
    "isotopoReferencia": "¹⁹⁵Pt",
    "massaAtomica": "195,084 u",
    "camadas": [
      2,
      8,
      18,
      32,
      17,
      1
    ],
    "distribuicao": "2–8–18–32–17–1",
    "grupo": 10,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "au",
    "nome": "Ouro",
    "simbolo": "Au",
    "numeroAtomico": 79,
    "barcode": 79,
    "protons": 79,
    "neutrons": 118,
    "eletrons": 79,
    "numeroMassa": 197,
    "isotopoReferencia": "¹⁹⁷Au",
    "massaAtomica": "196,967 u",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      1
    ],
    "distribuicao": "2–8–18–32–18–1",
    "grupo": 11,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal de transição"
  },
  {
    "id": "hg",
    "nome": "Mercúrio",
    "simbolo": "Hg",
    "numeroAtomico": 80,
    "barcode": 80,
    "protons": 80,
    "neutrons": 122,
    "eletrons": 80,
    "numeroMassa": 202,
    "isotopoReferencia": "²⁰²Hg",
    "massaAtomica": "200,59 u",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      2
    ],
    "distribuicao": "2–8–18–32–18–2",
    "grupo": 12,
    "periodo": 6,
    "bloco": "d",
    "classificacao": "Metal do grupo 12"
  },
  {
    "id": "tl",
    "nome": "Tálio",
    "simbolo": "Tl",
    "numeroAtomico": 81,
    "barcode": 81,
    "protons": 81,
    "neutrons": 124,
    "eletrons": 81,
    "numeroMassa": 205,
    "isotopoReferencia": "²⁰⁵Tl",
    "massaAtomica": "204,38 u",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      3
    ],
    "distribuicao": "2–8–18–32–18–3",
    "grupo": 13,
    "periodo": 6,
    "bloco": "p",
    "classificacao": "Metal pós-transição"
  },
  {
    "id": "pb",
    "nome": "Chumbo",
    "simbolo": "Pb",
    "numeroAtomico": 82,
    "barcode": 82,
    "protons": 82,
    "neutrons": 126,
    "eletrons": 82,
    "numeroMassa": 208,
    "isotopoReferencia": "²⁰⁸Pb",
    "massaAtomica": "207,2 u",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      4
    ],
    "distribuicao": "2–8–18–32–18–4",
    "grupo": 14,
    "periodo": 6,
    "bloco": "p",
    "classificacao": "Metal pós-transição"
  },
  {
    "id": "bi",
    "nome": "Bismuto",
    "simbolo": "Bi",
    "numeroAtomico": 83,
    "barcode": 83,
    "protons": 83,
    "neutrons": 126,
    "eletrons": 83,
    "numeroMassa": 209,
    "isotopoReferencia": "²⁰⁹Bi",
    "massaAtomica": "208,98 u",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      5
    ],
    "distribuicao": "2–8–18–32–18–5",
    "grupo": 15,
    "periodo": 6,
    "bloco": "p",
    "classificacao": "Metal pós-transição"
  },
  {
    "id": "po",
    "nome": "Polônio",
    "simbolo": "Po",
    "numeroAtomico": 84,
    "barcode": 84,
    "protons": 84,
    "neutrons": 125,
    "eletrons": 84,
    "numeroMassa": 209,
    "isotopoReferencia": "²⁰⁹Po",
    "massaAtomica": "[209]",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      6
    ],
    "distribuicao": "2–8–18–32–18–6",
    "grupo": 16,
    "periodo": 6,
    "bloco": "p",
    "classificacao": "Calcogênio radioativo"
  },
  {
    "id": "at",
    "nome": "Astato",
    "simbolo": "At",
    "numeroAtomico": 85,
    "barcode": 85,
    "protons": 85,
    "neutrons": 125,
    "eletrons": 85,
    "numeroMassa": 210,
    "isotopoReferencia": "²¹⁰At",
    "massaAtomica": "[210]",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      7
    ],
    "distribuicao": "2–8–18–32–18–7",
    "grupo": 17,
    "periodo": 6,
    "bloco": "p",
    "classificacao": "Halogênio radioativo"
  },
  {
    "id": "rn",
    "nome": "Radônio",
    "simbolo": "Rn",
    "numeroAtomico": 86,
    "barcode": 86,
    "protons": 86,
    "neutrons": 136,
    "eletrons": 86,
    "numeroMassa": 222,
    "isotopoReferencia": "²²²Rn",
    "massaAtomica": "[222]",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      8
    ],
    "distribuicao": "2–8–18–32–18–8",
    "grupo": 18,
    "periodo": 6,
    "bloco": "p",
    "classificacao": "Gás nobre radioativo"
  },
  {
    "id": "fr",
    "nome": "Frâncio",
    "simbolo": "Fr",
    "numeroAtomico": 87,
    "barcode": 87,
    "protons": 87,
    "neutrons": 136,
    "eletrons": 87,
    "numeroMassa": 223,
    "isotopoReferencia": "²²³Fr",
    "massaAtomica": "[223]",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      8,
      1
    ],
    "distribuicao": "2–8–18–32–18–8–1",
    "grupo": 1,
    "periodo": 7,
    "bloco": "s",
    "classificacao": "Metal alcalino radioativo"
  },
  {
    "id": "ra",
    "nome": "Rádio",
    "simbolo": "Ra",
    "numeroAtomico": 88,
    "barcode": 88,
    "protons": 88,
    "neutrons": 138,
    "eletrons": 88,
    "numeroMassa": 226,
    "isotopoReferencia": "²²⁶Ra",
    "massaAtomica": "[226]",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–18–8–2",
    "grupo": 2,
    "periodo": 7,
    "bloco": "s",
    "classificacao": "Metal alcalino-terroso radioativo"
  },
  {
    "id": "ac",
    "nome": "Actínio",
    "simbolo": "Ac",
    "numeroAtomico": 89,
    "barcode": 89,
    "protons": 89,
    "neutrons": 138,
    "eletrons": 89,
    "numeroMassa": 227,
    "isotopoReferencia": "²²⁷Ac",
    "massaAtomica": "[227]",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      9,
      2
    ],
    "distribuicao": "2–8–18–32–18–9–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "d / início dos actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "th",
    "nome": "Tório",
    "simbolo": "Th",
    "numeroAtomico": 90,
    "barcode": 90,
    "protons": 90,
    "neutrons": 142,
    "eletrons": 90,
    "numeroMassa": 232,
    "isotopoReferencia": "²³²Th",
    "massaAtomica": "232.04",
    "camadas": [
      2,
      8,
      18,
      32,
      18,
      10,
      2
    ],
    "distribuicao": "2–8–18–32–18–10–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / início dos actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "pa",
    "nome": "Protactínio",
    "simbolo": "Pa",
    "numeroAtomico": 91,
    "barcode": 91,
    "protons": 91,
    "neutrons": 140,
    "eletrons": 91,
    "numeroMassa": 231,
    "isotopoReferencia": "²³¹Pa",
    "massaAtomica": "231.04",
    "camadas": [
      2,
      8,
      18,
      32,
      20,
      9,
      2
    ],
    "distribuicao": "2–8–18–32–20–9–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "u",
    "nome": "Urânio",
    "simbolo": "U",
    "numeroAtomico": 92,
    "barcode": 92,
    "protons": 92,
    "neutrons": 146,
    "eletrons": 92,
    "numeroMassa": 238,
    "isotopoReferencia": "²³⁸U",
    "massaAtomica": "238.03",
    "camadas": [
      2,
      8,
      18,
      32,
      21,
      9,
      2
    ],
    "distribuicao": "2–8–18–32–21–9–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "np",
    "nome": "Netúnio",
    "simbolo": "Np",
    "numeroAtomico": 93,
    "barcode": 93,
    "protons": 93,
    "neutrons": 144,
    "eletrons": 93,
    "numeroMassa": 237,
    "isotopoReferencia": "²³⁷Np",
    "massaAtomica": "237",
    "camadas": [
      2,
      8,
      18,
      32,
      22,
      9,
      2
    ],
    "distribuicao": "2–8–18–32–22–9–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "pu",
    "nome": "Plutônio",
    "simbolo": "Pu",
    "numeroAtomico": 94,
    "barcode": 94,
    "protons": 94,
    "neutrons": 150,
    "eletrons": 94,
    "numeroMassa": 244,
    "isotopoReferencia": "²⁴⁴Pu",
    "massaAtomica": "244",
    "camadas": [
      2,
      8,
      18,
      32,
      24,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–24–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "am",
    "nome": "Amerício",
    "simbolo": "Am",
    "numeroAtomico": 95,
    "barcode": 95,
    "protons": 95,
    "neutrons": 148,
    "eletrons": 95,
    "numeroMassa": 243,
    "isotopoReferencia": "²⁴³Am",
    "massaAtomica": "243",
    "camadas": [
      2,
      8,
      18,
      32,
      25,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–25–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "cm",
    "nome": "Cúrio",
    "simbolo": "Cm",
    "numeroAtomico": 96,
    "barcode": 96,
    "protons": 96,
    "neutrons": 151,
    "eletrons": 96,
    "numeroMassa": 247,
    "isotopoReferencia": "²⁴⁷Cm",
    "massaAtomica": "247",
    "camadas": [
      2,
      8,
      18,
      32,
      25,
      9,
      2
    ],
    "distribuicao": "2–8–18–32–25–9–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "bk",
    "nome": "Berquélio",
    "simbolo": "Bk",
    "numeroAtomico": 97,
    "barcode": 97,
    "protons": 97,
    "neutrons": 150,
    "eletrons": 97,
    "numeroMassa": 247,
    "isotopoReferencia": "²⁴⁷Bk",
    "massaAtomica": "247",
    "camadas": [
      2,
      8,
      18,
      32,
      27,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–27–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "cf",
    "nome": "Califórnio",
    "simbolo": "Cf",
    "numeroAtomico": 98,
    "barcode": 98,
    "protons": 98,
    "neutrons": 153,
    "eletrons": 98,
    "numeroMassa": 251,
    "isotopoReferencia": "²⁵¹Cf",
    "massaAtomica": "251",
    "camadas": [
      2,
      8,
      18,
      32,
      28,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–28–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "es",
    "nome": "Einstênio",
    "simbolo": "Es",
    "numeroAtomico": 99,
    "barcode": 99,
    "protons": 99,
    "neutrons": 153,
    "eletrons": 99,
    "numeroMassa": 252,
    "isotopoReferencia": "²⁵²Es",
    "massaAtomica": "252",
    "camadas": [
      2,
      8,
      18,
      32,
      29,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–29–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "fm",
    "nome": "Férmio",
    "simbolo": "Fm",
    "numeroAtomico": 100,
    "barcode": 100,
    "protons": 100,
    "neutrons": 157,
    "eletrons": 100,
    "numeroMassa": 257,
    "isotopoReferencia": "²⁵⁷Fm",
    "massaAtomica": "257",
    "camadas": [
      2,
      8,
      18,
      32,
      30,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–30–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "md",
    "nome": "Mendelévio",
    "simbolo": "Md",
    "numeroAtomico": 101,
    "barcode": 101,
    "protons": 101,
    "neutrons": 157,
    "eletrons": 101,
    "numeroMassa": 258,
    "isotopoReferencia": "²⁵⁸Md",
    "massaAtomica": "258",
    "camadas": [
      2,
      8,
      18,
      32,
      31,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–31–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "no",
    "nome": "Nobélio",
    "simbolo": "No",
    "numeroAtomico": 102,
    "barcode": 102,
    "protons": 102,
    "neutrons": 157,
    "eletrons": 102,
    "numeroMassa": 259,
    "isotopoReferencia": "²⁵⁹No",
    "massaAtomica": "259",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      8,
      2
    ],
    "distribuicao": "2–8–18–32–32–8–2",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / actinídeos",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "lr",
    "nome": "Laurêncio",
    "simbolo": "Lr",
    "numeroAtomico": 103,
    "barcode": 103,
    "protons": 103,
    "neutrons": 163,
    "eletrons": 103,
    "numeroMassa": 266,
    "isotopoReferencia": "²⁶⁶Lr",
    "massaAtomica": "266",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      8,
      3
    ],
    "distribuicao": "2–8–18–32–32–8–3",
    "grupo": 3,
    "periodo": 7,
    "bloco": "f / fim dos actinídeos; configuração termina em 7p¹",
    "classificacao": "Metal actinídeo radioativo"
  },
  {
    "id": "rf",
    "nome": "Rutherfórdio",
    "simbolo": "Rf",
    "numeroAtomico": 104,
    "barcode": 104,
    "protons": 104,
    "neutrons": 163,
    "eletrons": 104,
    "numeroMassa": 267,
    "isotopoReferencia": "²⁶⁷Rf",
    "massaAtomica": "267",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      10,
      2
    ],
    "distribuicao": "2–8–18–32–32–10–2",
    "grupo": 4,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "db",
    "nome": "Dúbnio",
    "simbolo": "Db",
    "numeroAtomico": 105,
    "barcode": 105,
    "protons": 105,
    "neutrons": 163,
    "eletrons": 105,
    "numeroMassa": 268,
    "isotopoReferencia": "²⁶⁸Db",
    "massaAtomica": "268",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      11,
      2
    ],
    "distribuicao": "2–8–18–32–32–11–2",
    "grupo": 5,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "sg",
    "nome": "Seabórgio",
    "simbolo": "Sg",
    "numeroAtomico": 106,
    "barcode": 106,
    "protons": 106,
    "neutrons": 163,
    "eletrons": 106,
    "numeroMassa": 269,
    "isotopoReferencia": "²⁶⁹Sg",
    "massaAtomica": "269",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      12,
      2
    ],
    "distribuicao": "2–8–18–32–32–12–2",
    "grupo": 6,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "bh",
    "nome": "Bóhrio",
    "simbolo": "Bh",
    "numeroAtomico": 107,
    "barcode": 107,
    "protons": 107,
    "neutrons": 163,
    "eletrons": 107,
    "numeroMassa": 270,
    "isotopoReferencia": "²⁷⁰Bh",
    "massaAtomica": "270",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      13,
      2
    ],
    "distribuicao": "2–8–18–32–32–13–2",
    "grupo": 7,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "hs",
    "nome": "Hássio",
    "simbolo": "Hs",
    "numeroAtomico": 108,
    "barcode": 108,
    "protons": 108,
    "neutrons": 161,
    "eletrons": 108,
    "numeroMassa": 269,
    "isotopoReferencia": "²⁶⁹Hs",
    "massaAtomica": "[269]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      14,
      2
    ],
    "distribuicao": "2–8–18–32–32–14–2",
    "grupo": 8,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "mt",
    "nome": "Meitnério",
    "simbolo": "Mt",
    "numeroAtomico": 109,
    "barcode": 109,
    "protons": 109,
    "neutrons": 169,
    "eletrons": 109,
    "numeroMassa": 278,
    "isotopoReferencia": "²⁷⁸Mt",
    "massaAtomica": "[278]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      15,
      2
    ],
    "distribuicao": "2–8–18–32–32–15–2",
    "grupo": 9,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "ds",
    "nome": "Darmstádtio",
    "simbolo": "Ds",
    "numeroAtomico": 110,
    "barcode": 110,
    "protons": 110,
    "neutrons": 171,
    "eletrons": 110,
    "numeroMassa": 281,
    "isotopoReferencia": "²⁸¹Ds",
    "massaAtomica": "[281]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      17,
      1
    ],
    "distribuicao": "2–8–18–32–32–17–1",
    "grupo": 10,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "rg",
    "nome": "Roentgênio",
    "simbolo": "Rg",
    "numeroAtomico": 111,
    "barcode": 111,
    "protons": 111,
    "neutrons": 171,
    "eletrons": 111,
    "numeroMassa": 282,
    "isotopoReferencia": "²⁸²Rg",
    "massaAtomica": "[282]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      1
    ],
    "distribuicao": "2–8–18–32–32–18–1",
    "grupo": 11,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e radioativo"
  },
  {
    "id": "cn",
    "nome": "Copernício",
    "simbolo": "Cn",
    "numeroAtomico": 112,
    "barcode": 112,
    "protons": 112,
    "neutrons": 173,
    "eletrons": 112,
    "numeroMassa": 285,
    "isotopoReferencia": "²⁸⁵Cn",
    "massaAtomica": "[285]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      2
    ],
    "distribuicao": "2–8–18–32–32–18–2",
    "grupo": 12,
    "periodo": 7,
    "bloco": "d",
    "classificacao": "Metal de transição sintético e altamente radioativo"
  },
  {
    "id": "nh",
    "nome": "Nihônio",
    "simbolo": "Nh",
    "numeroAtomico": 113,
    "barcode": 113,
    "protons": 113,
    "neutrons": 173,
    "eletrons": 113,
    "numeroMassa": 286,
    "isotopoReferencia": "²⁸⁶Nh",
    "massaAtomica": "[286]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      3
    ],
    "distribuicao": "2–8–18–32–32–18–3",
    "grupo": 13,
    "periodo": 7,
    "bloco": "p",
    "classificacao": "Elemento sintético, superpesado e radioativo do grupo 13"
  },
  {
    "id": "fl",
    "nome": "Fleróvio",
    "simbolo": "Fl",
    "numeroAtomico": 114,
    "barcode": 114,
    "protons": 114,
    "neutrons": 175,
    "eletrons": 114,
    "numeroMassa": 289,
    "isotopoReferencia": "²⁸⁹Fl",
    "massaAtomica": "[289]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      4
    ],
    "distribuicao": "2–8–18–32–32–18–4",
    "grupo": 14,
    "periodo": 7,
    "bloco": "p",
    "classificacao": "Elemento superpesado sintético e radioativo do grupo 14"
  },
  {
    "id": "mc",
    "nome": "Moscóvio",
    "simbolo": "Mc",
    "numeroAtomico": 115,
    "barcode": 115,
    "protons": 115,
    "neutrons": 175,
    "eletrons": 115,
    "numeroMassa": 290,
    "isotopoReferencia": "²⁹⁰Mc",
    "massaAtomica": "[290]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      5
    ],
    "distribuicao": "2–8–18–32–32–18–5",
    "grupo": 15,
    "periodo": 7,
    "bloco": "p",
    "classificacao": "Elemento superpesado sintético e radioativo do grupo 15"
  },
  {
    "id": "lv",
    "nome": "Livermório",
    "simbolo": "Lv",
    "numeroAtomico": 116,
    "barcode": 116,
    "protons": 116,
    "neutrons": 177,
    "eletrons": 116,
    "numeroMassa": 293,
    "isotopoReferencia": "²⁹³Lv",
    "massaAtomica": "[293]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      6
    ],
    "distribuicao": "2–8–18–32–32–18–6",
    "grupo": 16,
    "periodo": 7,
    "bloco": "p",
    "classificacao": "Elemento superpesado sintético e radioativo do grupo 16"
  },
  {
    "id": "ts",
    "nome": "Tenessino",
    "simbolo": "Ts",
    "numeroAtomico": 117,
    "barcode": 117,
    "protons": 117,
    "neutrons": 177,
    "eletrons": 117,
    "numeroMassa": 294,
    "isotopoReferencia": "²⁹⁴Ts",
    "massaAtomica": "[294]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      7
    ],
    "distribuicao": "2–8–18–32–32–18–7",
    "grupo": 17,
    "periodo": 7,
    "bloco": "p",
    "classificacao": "Halogênio superpesado sintético e radioativo"
  },
  {
    "id": "og",
    "nome": "Oganessônio",
    "simbolo": "Og",
    "numeroAtomico": 118,
    "barcode": 118,
    "protons": 118,
    "neutrons": 176,
    "eletrons": 118,
    "numeroMassa": 294,
    "isotopoReferencia": "²⁹⁴Og",
    "massaAtomica": "[294]",
    "camadas": [
      2,
      8,
      18,
      32,
      32,
      18,
      8
    ],
    "distribuicao": "2–8–18–32–32–18–8",
    "grupo": 18,
    "periodo": 7,
    "bloco": "p",
    "classificacao": "Gás nobre superpesado, sintético e radioativo"
  }
];
