window.ISOTOPOS_NNDC = {
  "meta": {
    "projeto": "Tabela Periódica RA - Laboratório",
    "versaoBanco": "6.1-bloco-H-Ne",
    "fontePrimaria": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
    "fontePrimariaUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
    "fonteValidacao": "NNDC/ENSDF quando necessário",
    "consulta": "2026-09-03",
    "politica": "Somente estados fundamentais; isômeros/metastáveis excluídos do modo didático.",
    "regraReferencia": "isótopo natural mais abundante; em elementos sem abundância natural, será usado o estado fundamental de maior meia-vida nos próximos blocos.",
    "regraNavegacao": "±n somente se existir nuclídeo NNDC com A exatamente ±1; lacunas não são puladas.",
    "bloco": "H a Ne (Z=1–10), mantendo Na-22/23/24 como piloto já validado."
  },
  "elementos": {
    "H": {
      "Z": 1,
      "referenciaA": 1,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 1,
          "N": 0,
          "nuclideo": "1H",
          "simboloNuclear": "¹H",
          "nome": "Hidrogênio-1",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "99.972–99.999%",
          "abundanciaNaturalTexto": "99.972–99.999%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 2,
          "N": 1,
          "nuclideo": "2H",
          "simboloNuclear": "²H",
          "nome": "Hidrogênio-2",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "0.001–0.028%",
          "abundanciaNaturalTexto": "0.001–0.028%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 3,
          "N": 2,
          "nuclideo": "3H",
          "simboloNuclear": "³H",
          "nome": "Hidrogênio-3",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "12.322 anos",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 4,
          "N": 3,
          "nuclideo": "4H",
          "simboloNuclear": "⁴H",
          "nome": "Hidrogênio-4",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "3.3 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 5,
          "N": 4,
          "nuclideo": "5H",
          "simboloNuclear": "⁵H",
          "nome": "Hidrogênio-5",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "5.3 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2n ≈ 100%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 6,
          "N": 5,
          "nuclideo": "6H",
          "simboloNuclear": "⁶H",
          "nome": "Hidrogênio-6",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "1.5 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "3n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 7,
          "N": 6,
          "nuclideo": "7H",
          "simboloNuclear": "⁷H",
          "nome": "Hidrogênio-7",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "0.18 MeV (+0.47/−0.13 MeV)",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "4n?, 2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "He": {
      "Z": 2,
      "referenciaA": 4,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 3,
          "N": 1,
          "nuclideo": "3He",
          "simboloNuclear": "³He",
          "nome": "Hélio-3",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "0.0002%",
          "abundanciaNaturalTexto": "0.0002%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 4,
          "N": 2,
          "nuclideo": "4He",
          "simboloNuclear": "⁴He",
          "nome": "Hélio-4",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "99.9998%",
          "abundanciaNaturalTexto": "99.9998%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 5,
          "N": 3,
          "nuclideo": "5He",
          "simboloNuclear": "⁵He",
          "nome": "Hélio-5",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "719 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 6,
          "N": 4,
          "nuclideo": "6He",
          "simboloNuclear": "⁶He",
          "nome": "Hélio-6",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "807.12 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 7,
          "N": 5,
          "nuclideo": "7He",
          "simboloNuclear": "⁷He",
          "nome": "Hélio-7",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "195 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 8,
          "N": 6,
          "nuclideo": "8He",
          "simboloNuclear": "⁸He",
          "nome": "Hélio-8",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "119.0 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 16%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 9,
          "N": 7,
          "nuclideo": "9He",
          "simboloNuclear": "⁹He",
          "nome": "Hélio-9",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "1.8×10² keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 10,
          "N": 8,
          "nuclideo": "10He",
          "simboloNuclear": "¹⁰He",
          "nome": "Hélio-10",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "1.8 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "Li": {
      "Z": 3,
      "referenciaA": 7,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 4,
          "N": 1,
          "nuclideo": "4Li",
          "simboloNuclear": "⁴Li",
          "nome": "Lítio-4",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "5.0 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 5,
          "N": 2,
          "nuclideo": "5Li",
          "simboloNuclear": "⁵Li",
          "nome": "Lítio-5",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "1.23 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 6,
          "N": 3,
          "nuclideo": "6Li",
          "simboloNuclear": "⁶Li",
          "nome": "Lítio-6",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "1.9–7.8%",
          "abundanciaNaturalTexto": "1.9–7.8%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 7,
          "N": 4,
          "nuclideo": "7Li",
          "simboloNuclear": "⁷Li",
          "nome": "Lítio-7",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "92.2–98.1%",
          "abundanciaNaturalTexto": "92.2–98.1%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 8,
          "N": 5,
          "nuclideo": "8Li",
          "simboloNuclear": "⁸Li",
          "nome": "Lítio-8",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "838.79 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−α",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 9,
          "N": 6,
          "nuclideo": "9Li",
          "simboloNuclear": "⁹Li",
          "nome": "Lítio-9",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "178.0 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−α = 12.3%; β−n = 51.0%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 10,
          "N": 7,
          "nuclideo": "10Li",
          "simboloNuclear": "¹⁰Li",
          "nome": "Lítio-10",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "≤ 0.23 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 11,
          "N": 8,
          "nuclideo": "11Li",
          "simboloNuclear": "¹¹Li",
          "nome": "Lítio-11",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "8.75 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 84.3%; β−2n = 4.2%; β−3n = 1.9%; β−α = 1.7%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 12,
          "N": 9,
          "nuclideo": "12Li",
          "simboloNuclear": "¹²Li",
          "nome": "Lítio-12",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "sem_medida",
          "medidaRotulo": "T₁/₂ / Γ",
          "medidaTexto": "não indicada na Wallet Card",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 13,
          "N": 10,
          "nuclideo": "13Li",
          "simboloNuclear": "¹³Li",
          "nome": "Lítio-13",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "1.3×10² keV (+6/−4 keV)",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "Be": {
      "Z": 4,
      "referenciaA": 9,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 6,
          "N": 2,
          "nuclideo": "6Be",
          "simboloNuclear": "⁶Be",
          "nome": "Berílio-6",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "92 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 7,
          "N": 3,
          "nuclideo": "7Be",
          "simboloNuclear": "⁷Be",
          "nome": "Berílio-7",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "53.30 dias",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε (captura eletrônica)",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 8,
          "N": 4,
          "nuclideo": "8Be",
          "simboloNuclear": "⁸Be",
          "nome": "Berílio-8",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "5.57 eV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "α",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 9,
          "N": 5,
          "nuclideo": "9Be",
          "simboloNuclear": "⁹Be",
          "nome": "Berílio-9",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "100%",
          "abundanciaNaturalTexto": "100%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 10,
          "N": 6,
          "nuclideo": "10Be",
          "simboloNuclear": "¹⁰Be",
          "nome": "Berílio-10",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "1.386×10⁶ anos",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 11,
          "N": 7,
          "nuclideo": "11Be",
          "simboloNuclear": "¹¹Be",
          "nome": "Berílio-11",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "13.77 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−p = 0.000013%; β−α = 3.3%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 12,
          "N": 8,
          "nuclideo": "12Be",
          "simboloNuclear": "¹²Be",
          "nome": "Berílio-12",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "21.46 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 0.50%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 13,
          "N": 9,
          "nuclideo": "13Be",
          "simboloNuclear": "¹³Be",
          "nome": "Berílio-13",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "450 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 14,
          "N": 10,
          "nuclideo": "14Be",
          "simboloNuclear": "¹⁴Be",
          "nome": "Berílio-14",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "4.65 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 86%; β−2n = 5%; β−α < 0.004%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 15,
          "N": 11,
          "nuclideo": "15Be",
          "simboloNuclear": "¹⁵Be",
          "nome": "Berílio-15",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "5.8×10² keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 16,
          "N": 12,
          "nuclideo": "16Be",
          "simboloNuclear": "¹⁶Be",
          "nome": "Berílio-16",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "0.8 MeV (+0.1/−0.2 MeV)",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "B": {
      "Z": 5,
      "referenciaA": 11,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 7,
          "N": 2,
          "nuclideo": "7B",
          "simboloNuclear": "⁷B",
          "nome": "Boro-7",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "801 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p ≈ 100%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 8,
          "N": 3,
          "nuclideo": "8B",
          "simboloNuclear": "⁸B",
          "nome": "Boro-8",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "772.1 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+; εα",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 9,
          "N": 4,
          "nuclideo": "9B",
          "simboloNuclear": "⁹B",
          "nome": "Boro-9",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "5.4×10² eV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 10,
          "N": 5,
          "nuclideo": "10B",
          "simboloNuclear": "¹⁰B",
          "nome": "Boro-10",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "18.9–20.4%",
          "abundanciaNaturalTexto": "18.9–20.4%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 11,
          "N": 6,
          "nuclideo": "11B",
          "simboloNuclear": "¹¹B",
          "nome": "Boro-11",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "79.6–81.1%",
          "abundanciaNaturalTexto": "79.6–81.1%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 12,
          "N": 7,
          "nuclideo": "12B",
          "simboloNuclear": "¹²B",
          "nome": "Boro-12",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "20.22 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−α = 0.60%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 13,
          "N": 8,
          "nuclideo": "13B",
          "simboloNuclear": "¹³B",
          "nome": "Boro-13",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "17.16 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 0.266%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 14,
          "N": 9,
          "nuclideo": "14B",
          "simboloNuclear": "¹⁴B",
          "nome": "Boro-14",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "12.34 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 6.04%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 15,
          "N": 10,
          "nuclideo": "15B",
          "simboloNuclear": "¹⁵B",
          "nome": "Boro-15",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "10.18 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 99.7%; β−2n < 1.5%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 16,
          "N": 11,
          "nuclideo": "16B",
          "simboloNuclear": "¹⁶B",
          "nome": "Boro-16",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "< 100 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 17,
          "N": 12,
          "nuclideo": "17B",
          "simboloNuclear": "¹⁷B",
          "nome": "Boro-17",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "5.07 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 63%; β−2n = 12%; β−3n = 3.5%; β−4n = 0.4%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 18,
          "N": 13,
          "nuclideo": "18B",
          "simboloNuclear": "¹⁸B",
          "nome": "Boro-18",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "sem_medida",
          "medidaRotulo": "T₁/₂ / Γ",
          "medidaTexto": "não indicada na Wallet Card",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 19,
          "N": 14,
          "nuclideo": "19B",
          "simboloNuclear": "¹⁹B",
          "nome": "Boro-19",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "2.92 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 72%; β−2n = 16%; β−3n < 9.1%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 20,
          "N": 15,
          "nuclideo": "20B",
          "simboloNuclear": "²⁰B",
          "nome": "Boro-20",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "≤ 500 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 21,
          "N": 16,
          "nuclideo": "21B",
          "simboloNuclear": "²¹B",
          "nome": "Boro-21",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "≤ 600 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "C": {
      "Z": 6,
      "referenciaA": 12,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 8,
          "N": 2,
          "nuclideo": "8C",
          "simboloNuclear": "⁸C",
          "nome": "Carbono-8",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "1.3×10² keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 9,
          "N": 3,
          "nuclideo": "9C",
          "simboloNuclear": "⁹C",
          "nome": "Carbono-9",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "126.5 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+; εp = 62.0%; εα = 38%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 10,
          "N": 4,
          "nuclideo": "10C",
          "simboloNuclear": "¹⁰C",
          "nome": "Carbono-10",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "19.3015 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 11,
          "N": 5,
          "nuclideo": "11C",
          "simboloNuclear": "¹¹C",
          "nome": "Carbono-11",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "20.3401 min",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 12,
          "N": 6,
          "nuclideo": "12C",
          "simboloNuclear": "¹²C",
          "nome": "Carbono-12",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "98.84–99.04%",
          "abundanciaNaturalTexto": "98.84–99.04%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 13,
          "N": 7,
          "nuclideo": "13C",
          "simboloNuclear": "¹³C",
          "nome": "Carbono-13",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "0.96–1.16%",
          "abundanciaNaturalTexto": "0.96–1.16%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 14,
          "N": 8,
          "nuclideo": "14C",
          "simboloNuclear": "¹⁴C",
          "nome": "Carbono-14",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "5686 anos",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 15,
          "N": 9,
          "nuclideo": "15C",
          "simboloNuclear": "¹⁵C",
          "nome": "Carbono-15",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "2.451 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 16,
          "N": 10,
          "nuclideo": "16C",
          "simboloNuclear": "¹⁶C",
          "nome": "Carbono-16",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "750 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 99.28%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 17,
          "N": 11,
          "nuclideo": "17C",
          "simboloNuclear": "¹⁷C",
          "nome": "Carbono-17",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "193 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 28.4%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 18,
          "N": 12,
          "nuclideo": "18C",
          "simboloNuclear": "¹⁸C",
          "nome": "Carbono-18",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "92 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 31.5%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 19,
          "N": 13,
          "nuclideo": "19C",
          "simboloNuclear": "¹⁹C",
          "nome": "Carbono-19",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "46.3 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 47%; β−2n = 7%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 20,
          "N": 14,
          "nuclideo": "20C",
          "simboloNuclear": "²⁰C",
          "nome": "Carbono-20",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "16.0 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 66%; β−2n < 18.6%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 22,
          "N": 16,
          "nuclideo": "22C",
          "simboloNuclear": "²²C",
          "nome": "Carbono-22",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "6.1 ms (+1.4/−1.2 ms)",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 61%; β−2n < 37%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03",
          "observacao": "O NNDC não lista 21C nesta edição; o botão +n para em 20C para não saltar um nêutron."
        }
      ]
    },
    "N": {
      "Z": 7,
      "referenciaA": 14,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 10,
          "N": 3,
          "nuclideo": "10N",
          "simboloNuclear": "¹⁰N",
          "nome": "Nitrogênio-10",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "2.5 MeV (+2.0/−1.5 MeV)",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 11,
          "N": 4,
          "nuclideo": "11N",
          "simboloNuclear": "¹¹N",
          "nome": "Nitrogênio-11",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "780 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 12,
          "N": 5,
          "nuclideo": "12N",
          "simboloNuclear": "¹²N",
          "nome": "Nitrogênio-12",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "10.996 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+; εα = 1.93%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 13,
          "N": 6,
          "nuclideo": "13N",
          "simboloNuclear": "¹³N",
          "nome": "Nitrogênio-13",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "9.967 min",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 14,
          "N": 7,
          "nuclideo": "14N",
          "simboloNuclear": "¹⁴N",
          "nome": "Nitrogênio-14",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "99.578–99.663%",
          "abundanciaNaturalTexto": "99.578–99.663%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 15,
          "N": 8,
          "nuclideo": "15N",
          "simboloNuclear": "¹⁵N",
          "nome": "Nitrogênio-15",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "0.337–0.422%",
          "abundanciaNaturalTexto": "0.337–0.422%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 16,
          "N": 9,
          "nuclideo": "16N",
          "simboloNuclear": "¹⁶N",
          "nome": "Nitrogênio-16",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "7.13 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−α = 0.00154%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 17,
          "N": 10,
          "nuclideo": "17N",
          "simboloNuclear": "¹⁷N",
          "nome": "Nitrogênio-17",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "4.171 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 95.1%; β−α = 0.0025%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 18,
          "N": 11,
          "nuclideo": "18N",
          "simboloNuclear": "¹⁸N",
          "nome": "Nitrogênio-18",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "619 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 8.3%; β−α = 12.2%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 19,
          "N": 12,
          "nuclideo": "19N",
          "simboloNuclear": "¹⁹N",
          "nome": "Nitrogênio-19",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "336 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 41.8%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 20,
          "N": 13,
          "nuclideo": "20N",
          "simboloNuclear": "²⁰N",
          "nome": "Nitrogênio-20",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "136 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 42.9%; β−2n ≈ 4.5%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 21,
          "N": 14,
          "nuclideo": "21N",
          "simboloNuclear": "²¹N",
          "nome": "Nitrogênio-21",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "85.3 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 86.5%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 22,
          "N": 15,
          "nuclideo": "22N",
          "simboloNuclear": "²²N",
          "nome": "Nitrogênio-22",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "20.9 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 34%; β−2n = 12%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 23,
          "N": 16,
          "nuclideo": "23N",
          "simboloNuclear": "²³N",
          "nome": "Nitrogênio-23",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "14.1 ms (+1.2/−1.5 ms)",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 42%; β−2n = 8%; β−3n < 3.4%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 24,
          "N": 17,
          "nuclideo": "24N",
          "simboloNuclear": "²⁴N",
          "nome": "Nitrogênio-24",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "< 52 ns",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "O": {
      "Z": 8,
      "referenciaA": 16,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 11,
          "N": 3,
          "nuclideo": "11O",
          "simboloNuclear": "¹¹O",
          "nome": "Oxigênio-11",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "2.31 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 12,
          "N": 4,
          "nuclideo": "12O",
          "simboloNuclear": "¹²O",
          "nome": "Oxigênio-12",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "51 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 13,
          "N": 5,
          "nuclideo": "13O",
          "simboloNuclear": "¹³O",
          "nome": "Oxigênio-13",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "8.58 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+; εp = 10.8%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 14,
          "N": 6,
          "nuclideo": "14O",
          "simboloNuclear": "¹⁴O",
          "nome": "Oxigênio-14",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "70.618 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 15,
          "N": 7,
          "nuclideo": "15O",
          "simboloNuclear": "¹⁵O",
          "nome": "Oxigênio-15",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "122.268 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 16,
          "N": 8,
          "nuclideo": "16O",
          "simboloNuclear": "¹⁶O",
          "nome": "Oxigênio-16",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "99.738–99.776%",
          "abundanciaNaturalTexto": "99.738–99.776%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 17,
          "N": 9,
          "nuclideo": "17O",
          "simboloNuclear": "¹⁷O",
          "nome": "Oxigênio-17",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "0.0367–0.04%",
          "abundanciaNaturalTexto": "0.0367–0.04%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 18,
          "N": 10,
          "nuclideo": "18O",
          "simboloNuclear": "¹⁸O",
          "nome": "Oxigênio-18",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "0.187–0.222%",
          "abundanciaNaturalTexto": "0.187–0.222%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 19,
          "N": 11,
          "nuclideo": "19O",
          "simboloNuclear": "¹⁹O",
          "nome": "Oxigênio-19",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "26.470 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 20,
          "N": 12,
          "nuclideo": "20O",
          "simboloNuclear": "²⁰O",
          "nome": "Oxigênio-20",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "13.51 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 21,
          "N": 13,
          "nuclideo": "21O",
          "simboloNuclear": "²¹O",
          "nome": "Oxigênio-21",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "3.42 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 22,
          "N": 14,
          "nuclideo": "22O",
          "simboloNuclear": "²²O",
          "nome": "Oxigênio-22",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "2.19 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n < 22%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 23,
          "N": 15,
          "nuclideo": "23O",
          "simboloNuclear": "²³O",
          "nome": "Oxigênio-23",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "96 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 7%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 24,
          "N": 16,
          "nuclideo": "24O",
          "simboloNuclear": "²⁴O",
          "nome": "Oxigênio-24",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "72 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 41%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 25,
          "N": 17,
          "nuclideo": "25O",
          "simboloNuclear": "²⁵O",
          "nome": "Oxigênio-25",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "88 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 26,
          "N": 18,
          "nuclideo": "26O",
          "simboloNuclear": "²⁶O",
          "nome": "Oxigênio-26",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "0.0045 ns (+0.0032/−0.0034 ns)",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 28,
          "N": 20,
          "nuclideo": "28O",
          "simboloNuclear": "²⁸O",
          "nome": "Oxigênio-28",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "< 100 ns",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03",
          "observacao": "O NNDC não lista 27O nesta edição; a navegação +n para em 26O."
        }
      ]
    },
    "F": {
      "Z": 9,
      "referenciaA": 19,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 14,
          "N": 5,
          "nuclideo": "14F",
          "simboloNuclear": "¹⁴F",
          "nome": "Flúor-14",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "9.1×10² keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 15,
          "N": 6,
          "nuclideo": "15F",
          "simboloNuclear": "¹⁵F",
          "nome": "Flúor-15",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "0.38 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 16,
          "N": 7,
          "nuclideo": "16F",
          "simboloNuclear": "¹⁶F",
          "nome": "Flúor-16",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "23.1 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 17,
          "N": 8,
          "nuclideo": "17F",
          "simboloNuclear": "¹⁷F",
          "nome": "Flúor-17",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "64.368 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 18,
          "N": 9,
          "nuclideo": "18F",
          "simboloNuclear": "¹⁸F",
          "nome": "Flúor-18",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "109.734 min",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 19,
          "N": 10,
          "nuclideo": "19F",
          "simboloNuclear": "¹⁹F",
          "nome": "Flúor-19",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "100%",
          "abundanciaNaturalTexto": "100%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 20,
          "N": 11,
          "nuclideo": "20F",
          "simboloNuclear": "²⁰F",
          "nome": "Flúor-20",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "11.006 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 21,
          "N": 12,
          "nuclideo": "21F",
          "simboloNuclear": "²¹F",
          "nome": "Flúor-21",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "4.158 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 22,
          "N": 13,
          "nuclideo": "22F",
          "simboloNuclear": "²²F",
          "nome": "Flúor-22",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "4.23 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n < 11%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 23,
          "N": 14,
          "nuclideo": "23F",
          "simboloNuclear": "²³F",
          "nome": "Flúor-23",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "2.23 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n < 14%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 24,
          "N": 15,
          "nuclideo": "24F",
          "simboloNuclear": "²⁴F",
          "nome": "Flúor-24",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "384 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n < 5.9%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 25,
          "N": 16,
          "nuclideo": "25F",
          "simboloNuclear": "²⁵F",
          "nome": "Flúor-25",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "81 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 23.6%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 26,
          "N": 17,
          "nuclideo": "26F",
          "simboloNuclear": "²⁶F",
          "nome": "Flúor-26",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "8.6 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 14%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 27,
          "N": 18,
          "nuclideo": "27F",
          "simboloNuclear": "²⁷F",
          "nome": "Flúor-27",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "5.3 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 90%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 28,
          "N": 19,
          "nuclideo": "28F",
          "simboloNuclear": "²⁸F",
          "nome": "Flúor-28",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "180 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 29,
          "N": 20,
          "nuclideo": "29F",
          "simboloNuclear": "²⁹F",
          "nome": "Flúor-29",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "3.3 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 60%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 30,
          "N": 21,
          "nuclideo": "30F",
          "simboloNuclear": "³⁰F",
          "nome": "Flúor-30",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "< 250 ns",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 31,
          "N": 22,
          "nuclideo": "31F",
          "simboloNuclear": "³¹F",
          "nome": "Flúor-31",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "sem_medida",
          "medidaRotulo": "T₁/₂ / Γ",
          "medidaTexto": "não indicada na Wallet Card",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−?; β−n?; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "Ne": {
      "Z": 10,
      "referenciaA": 20,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 15,
          "N": 5,
          "nuclideo": "15Ne",
          "simboloNuclear": "¹⁵Ne",
          "nome": "Neônio-15",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "0.59 MeV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 16,
          "N": 6,
          "nuclideo": "16Ne",
          "simboloNuclear": "¹⁶Ne",
          "nome": "Neônio-16",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "largura",
          "medidaRotulo": "Largura de decaimento Γ",
          "medidaTexto": "< 80 keV",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "2p",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 17,
          "N": 7,
          "nuclideo": "17Ne",
          "simboloNuclear": "¹⁷Ne",
          "nome": "Neônio-17",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "109.1 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+; εp = 94.4%; εα = 3.51%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 18,
          "N": 8,
          "nuclideo": "18Ne",
          "simboloNuclear": "¹⁸Ne",
          "nome": "Neônio-18",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "1.6643 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 19,
          "N": 9,
          "nuclideo": "19Ne",
          "simboloNuclear": "¹⁹Ne",
          "nome": "Neônio-19",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "17.2569 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 20,
          "N": 10,
          "nuclideo": "20Ne",
          "simboloNuclear": "²⁰Ne",
          "nome": "Neônio-20",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "90.48%",
          "abundanciaNaturalTexto": "90.48%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 21,
          "N": 11,
          "nuclideo": "21Ne",
          "simboloNuclear": "²¹Ne",
          "nome": "Neônio-21",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "0.27%",
          "abundanciaNaturalTexto": "0.27%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 22,
          "N": 12,
          "nuclideo": "22Ne",
          "simboloNuclear": "²²Ne",
          "nome": "Neônio-22",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "9.25%",
          "abundanciaNaturalTexto": "9.25%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 23,
          "N": 13,
          "nuclideo": "23Ne",
          "simboloNuclear": "²³Ne",
          "nome": "Neônio-23",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "37.148 s",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 24,
          "N": 14,
          "nuclideo": "24Ne",
          "simboloNuclear": "²⁴Ne",
          "nome": "Neônio-24",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "3.38 min",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 25,
          "N": 15,
          "nuclideo": "25Ne",
          "simboloNuclear": "²⁵Ne",
          "nome": "Neônio-25",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "602 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 26,
          "N": 16,
          "nuclideo": "26Ne",
          "simboloNuclear": "²⁶Ne",
          "nome": "Neônio-26",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "196 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 0.13%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 27,
          "N": 17,
          "nuclideo": "27Ne",
          "simboloNuclear": "²⁷Ne",
          "nome": "Neônio-27",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "30.9 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 2.0%; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 28,
          "N": 18,
          "nuclideo": "28Ne",
          "simboloNuclear": "²⁸Ne",
          "nome": "Neônio-28",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "18.7 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 12%; β−2n = 3.7%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 29,
          "N": 19,
          "nuclideo": "29Ne",
          "simboloNuclear": "²⁹Ne",
          "nome": "Neônio-29",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "14.0 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 28%; β−2n = 4%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 30,
          "N": 20,
          "nuclideo": "30Ne",
          "simboloNuclear": "³⁰Ne",
          "nome": "Neônio-30",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "7.3 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n = 13%; β−2n = 8.9%",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 31,
          "N": 21,
          "nuclideo": "31Ne",
          "simboloNuclear": "³¹Ne",
          "nome": "Neônio-31",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "3.4 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n?; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 32,
          "N": 22,
          "nuclideo": "32Ne",
          "simboloNuclear": "³²Ne",
          "nome": "Neônio-32",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "4.5 ms",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−; β−n?; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 33,
          "N": 23,
          "nuclideo": "33Ne",
          "simboloNuclear": "³³Ne",
          "nome": "Neônio-33",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "< 180 ns",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 34,
          "N": 24,
          "nuclideo": "34Ne",
          "simboloNuclear": "³⁴Ne",
          "nome": "Neônio-34",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "instavel_nao_ligado",
          "medidaTipo": "sem_medida",
          "medidaRotulo": "T₁/₂ / Γ",
          "medidaTexto": "não indicada na Wallet Card",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−?; β−n?; β−2n?",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    },
    "Na": {
      "Z": 11,
      "referenciaA": 23,
      "criterioReferencia": "isótopo natural mais abundante",
      "isotopos": [
        {
          "A": 22,
          "N": 11,
          "nuclideo": "22Na",
          "simboloNuclear": "²²Na",
          "nome": "Sódio-22",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "2.60188 anos",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "ε + β+",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 23,
          "N": 12,
          "nuclideo": "23Na",
          "simboloNuclear": "²³Na",
          "nome": "Sódio-23",
          "estadoFundamental": true,
          "estavel": true,
          "classificacao": "estavel",
          "medidaTipo": "abundancia",
          "medidaRotulo": "Abundância natural",
          "medidaTexto": "100%",
          "abundanciaNaturalTexto": "100%",
          "modoDecaimentoResumo": null,
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        },
        {
          "A": 24,
          "N": 13,
          "nuclideo": "24Na",
          "simboloNuclear": "²⁴Na",
          "nome": "Sódio-24",
          "estadoFundamental": true,
          "estavel": false,
          "classificacao": "radioativo",
          "medidaTipo": "meia_vida",
          "medidaRotulo": "Meia-vida",
          "medidaTexto": "14.9578 h",
          "abundanciaNaturalTexto": null,
          "modoDecaimentoResumo": "β−",
          "fonte": "NNDC Nuclear Wallet Cards — standard_booklet.pdf",
          "fonteUrl": "https://www.nndc.bnl.gov/walletcards/doc/standard_booklet.pdf",
          "consulta": "2026-09-03"
        }
      ]
    }
  }
};
